stages:
- name: build
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: localnginx
      pushRemote: true
      registry: harbor.10.240.136.215.xip.io
timeout: 60
notification: {}
